// <auto-generated />
using DCProyectoPersMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCProyectoPersMVC.Migrations
{
    [DbContext(typeof(DCProyectoPersMVCContext))]
    partial class DCProyectoPersMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCProyectoPersMVC.Models.DCBebida", b =>
                {
                    b.Property<int>("DC_BebidaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DC_BebidaID"));

                    b.Property<string>("DC_Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DC_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DC_Tipo")
                        .HasColumnType("int");

                    b.HasKey("DC_BebidaID");

                    b.ToTable("DCBebida");
                });
#pragma warning restore 612, 618
        }
    }
}
